### ISSUE TITLE
Unable to deploy the quickstarter

### ISSUE THREAD

**Issue by kevingimbel** [aws-quickstart/quickstart-magento#27] opened 2018-02-28 16:17 UTC
Hello!

I am going crazy. I am unable to deploy the Magento Quickstarter Stack. I tried downloading and uploading all templates to my own S3 buckets as well as using the "Deploy" buttons from https://docs.aws.amazon.com/quickstart/latest/magento/step3.html

I tried to deploy in "my" prefered region (eu-central-1) as well as the default us-east-2 and both fail. The last failure I got was:

```
Embedded stack arn:aws:cloudformation:us-west-2:XXXXXXXXXX:stack/Magento-MagentoStack-1PD0YXCNWA476/6b009c20-1c9f-11e8-8a92-500c593b9a36 was not successfully created: The following resource(s) failed to create: [WebServerASGStack].
```

I used the "Deploy to new VPC" option and filled out all parameters best to my knowledge, yet it always fails both in eu-central-1 and us-east-2. 

Can anyone confirm that the template(s) are working? I cannot get them setup after spending hours of trying to find out what goes wrong. 

Any help is appreciated and if you need anything else from me I'm happy to provide anything I can.

**Comment by jvood** [comment] 2018-03-12 12:22
Hi! @kevingimbel 
I have the same issue.. Have you done something about this problem? I am really going crazy..

![Image of the Issue](https://i.imgur.com/Go0ya9g.png)

**Comment by santiagocardenas** [comment] 2018-03-12 18:05
The template is functional, I just checked our internal test deployments.

Some suggestions:

- Disable Rollback on failure. This allows you to see what's happened.
- Don't change the values of Quick Start S3 Bucket Name and Key Prefix, unless you are using your own set of customized templates from your own bucket.
- Ensure that you do have the correct tarball for Magento staged in your own S3 bucket for deployment.

**Comment by kevingimbel** [comment] 2018-03-13 09:10
@jvood We (my company) gave up on the quickstarter and instead used a Marketplace image for our Magento since it's only an internal test system at the moment. 

@santiagocardenas Thank you for your reply. I'll keep disabling "Rollback on failure" in mind when I try the next time, at the moment however my company doesn't want to invest more time into getting the quick starter deployed.

If I remember correctly I did try to deploy it without changing or adjusting anything and it failed, too.

**Comment by sshvans** [comment] 2018-06-01 17:20
@jvood I am closing it since we are not seeing this issue in our internal test deployments. Feel free to reopen it and attach logs/screenshots if you encounter this issue again.

**Closed by sshvans** 2018-06-01 17:20 UTC
Labels: invalid

**Comment by pangdaxing23** [comment] 2018-09-21 16:07
I have this same issue.
Tried deploying into new VPC.
I did not change the prefix or bucket name, and I used the correct tarball.
![image](https://user-images.githubusercontent.com/7274887/45892520-5f838900-bd96-11e8-9199-fa677fd53b0e.png)

**Comment by sshvans** [comment] 2018-09-21 16:51
@pangdaxing23 Can you provide the following details so that I can try to reproduce the issue.
- Input parameter values
- AWS region you launched the stack

**Comment by sunilvb** [comment] 2019-06-03 18:24
Unable to deploy quickstarter:
-new vpc
-magento CE 2.3.1 with Sample Data

Fails with following message:
Embedded stack arn:aws:cloudformation:us-west-2:652720305286:stack/Magento-MagentoStack-Q46DWU38G206/46288290-8626-11e9-9902-0aeceae62d6e was not successfully created: The following resource(s) failed to create: [WebServerASGStack].

**Comment by davidholbrook** [comment] 2019-06-21 14:44
The default aws quickstart only supports up to magneto v2.1.9 or below, to deploy with the current 2.3.1 version (as of writing) download this repo (https://github.com/joon73/quickstart-magento) to a S3 bucket with a copy of magneto and reference the `magento-master.template` from there.

**Comment by shiraski** [comment] 2020-05-31 13:59
Dear Friends i also try deploy magento aws quick start but i am facing this error
I am used template latest from github

1) Desired capacity:1 must be between the specified min size:2 and max size:2 (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: 2c01a8b7-3f56-47db-8915-5c1106b02e51)

2) Embedded stack arn:aws:cloudformation:ap-south-1:980552993969:stack/Magento-MagentoStack-QL4PX3FB7LRS-WebServerASGStack-1DW0XOX02LXYG/e1397e10-a33f-11ea-8029-02c26db14466 was not successfully created: The following resource(s) failed to create: [WebServerASG]. 

3) Embedded stack arn:aws:cloudformation:ap-south-1:980552993969:stack/Magento-MagentoStack-QL4PX3FB7LRS/5285d810-a33c-11ea-88c7-06184e58d994 was not successfully created: The following resource(s) failed to create: [WebServerASGStack].
